extent.reporter.spark.start=true
extent.reporter.spark.out=target/ExtentReports/ExtentReport.html


screenshot.dir=target/Screenshots/
screenshot.rel.path=../Screenshots/

basefolder.name=test-output/SparkReport